'use strict';

const { header, section, line, paint } = require('../ui');
const { info, success, warning, error } = require('../logger');
const {
  commandOutput,
  commandExists,
  packageManagerLabel,
  platformLabel,
  detectTerminal
} = require('../utils');
const { aliasStatus } = require('../alias');
const { validateConfig } = require('../validation');

function doctor(context) {
  header(context.config);

  section('Environment');
  printVersion('Node', 'node', ['--version']);
  printVersion(packageManagerLabel(context.config.packageManager), context.config.packageManager, ['--version']);
  printVersion('Git', 'git', ['--version']);
  success(platformLabel());
  success(`Terminal: ${detectTerminal().name}`);

  const editor = context.config.editor || 'code';
  printAvailable(`Editor (${editor})`, editor);

  section('Workspace');
  success(`${context.config.services.length} services`);
  printAlias(context);
  line(`    ${paint('root', 'dim')}         ${context.root}`);
  line(`    ${paint('launch mode', 'dim')}  ${context.config.launchMode}`);

  const warnings = validateConfig(context, { includeMissingCommands: true });

  if (warnings.length === 0) {
    success('config valid');
  } else {
    warning('config has warnings');
    warnings.forEach((item) => {
      warning(item.message);
      info(item.guidance);
    });
  }
}

function printVersion(label, command, args) {
  const version = commandOutput(command, args);

  if (version) {
    success(`${label}: ${version}`);
  } else {
    error(`${label}: missing`);
    info(`Install ${label} or make sure it is available on your PATH.`);
  }
}

function printAvailable(label, command) {
  if (commandExists(command)) {
    success(`${label}: available`);
  } else {
    warning(`${label}: unavailable`);
  }
}

function printAlias(context) {
  const status = aliasStatus(context.config.alias, context.root);

  if (!context.config.alias) {
    warning('alias missing');
    info('Run devpilot setup to choose an alias.');
    return;
  }

  if (!status.installed) {
    warning(`alias ${context.config.alias} not found on PATH`);
    info('Run devpilot setup to recreate the generated alias.');
    return;
  }

  if (!status.generated) {
    warning(`alias ${context.config.alias} exists but was not generated by DevPilot`);
    info(`Check ${status.path} before overwriting it.`);
    return;
  }

  if (!status.matchesProject) {
    warning(`alias ${context.config.alias} points to another project`);
    info('Run devpilot setup from this project root to refresh it.');
    return;
  }

  success(`alias installed: ${status.path}`);
}

module.exports = { doctor };
